// Generated by CoffeeScript 1.6.3
(function() {
  var express = require("express");

  var weixin = require("weixin-api");

  var routes = require("./routes");

  var user = require("./routes/user");

  var http = require("http");

  var path = require("path");

  var config = require('config');

  var app = express();

  app.set("port", process.env.PORT || 80);

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, "public")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/users", user.list);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

  app.use(express.bodyParser());
  
  weixin.token = config.get('wx.token');

  app.get("/wechat", function(req, res) {
    if (weixin.checkSignature(req)) {
      return res.send(200, req.query.echostr);
    } else {
      return res.send(200, "fail");
    }
  });

  weixin.textMsg(function(msg) {
    console.log("textMsg received");
    console.log(JSON.stringify(msg));

    var articles, reg, resMsg;
    resMsg = {
          fromUserName: msg.toUserName,
          toUserName: msg.fromUserName,
          msgType: "",
          content: "",
          funcFlag: 0
        };

    switch (msg.content) {
      case "jj":
        routes.getfund(msg, function(chosen_fund){
          console.log(chosen_fund);
          resMsg.msgType = "text";
          resMsg.content = chosen_fund;
          return weixin.sendMsg(resMsg);
        });
        break;
      case "yjtext":
        resMsg.msgType = "text";
        resMsg.content = "余静：温柔、漂亮、有气质、身材好、我心中的女神！[鼓掌]";
        return weixin.sendMsg(resMsg);
        break;
      case "ccc":
        resMsg.msgType = "text";
        resMsg.content = "陈显峰：[强]";
        return weixin.sendMsg(resMsg);
      break;
      case "音乐":
        resMsg = {
          fromUserName: msg.toUserName,
          toUserName: msg.fromUserName,
          msgType: "music",
          title: "音乐标题",
          description: "音乐描述",
          musicUrl: "音乐url",
          HQMusicUrl: "高质量音乐url",
          funcFlag: 0
        };
        return weixin.sendMsg(resMsg);
        break;
      case "yj":
        articles = [];
        articles[0] = {
          title: "I Love You And Thank You!",
          description: "小静，情人节快乐!",
          picUrl: "http://" + config.get('server.ip') + ":" + config.get('server.port') + "/images/0.jpg",
          url: "http://mp.weixin.qq.com/s?__biz=MzA3ODMwMDExMA==&mid=403057711&idx=1&sn=8cd5d90cded186e16c3acf5de87acd7e&scene=1&srcid=0204JSDHbCwsiYCN82TgGkYy#wechat_redirect"
        };
        resMsg.msgType = "news";
        resMsg.articles = articles;
        return weixin.sendMsg(resMsg);
        break;
        default:
        return weixin.sendMsg(resMsg);
        break;
    }
    //return weixin.sendMsg(resMsg);
  });

  weixin.imageMsg(function(msg) {
    console.log("imageMsg received");
    return console.log(JSON.stringify(msg));
  });

  weixin.locationMsg(function(msg) {
    console.log("locationMsg received");
    return console.log(JSON.stringify(msg));
  });

  weixin.urlMsg(function(msg) {
    console.log("urlMsg received");
    return console.log(JSON.stringify(msg));
  });

  weixin.eventMsg(function(msg) {
    console.log("eventMsg received");
    return console.log(JSON.stringify(msg));
  });

  app.post("/", function(req, res) {
    return weixin.loop(req, res);
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
